hx -added all things we need to connect book frontend and backend
ucsb-cs156-s23/team03-s23-7pm-3 pull request #22
Opened 2023-05-21 00:06 UTC by zihaoxu20010109

In this PR, I added all necessary things for connection of Book frontend and backend. TODO:TEST QA AND MUTATION

2023-05-21 09:25 UTC, wq12li reviewed
I've tested this branch on localhost, through the version already pushed to QA, and with local mutation/coverage testing on both frontend and backend: All methods seem to work correctly.

I just have a few suggestions for keeping some formatting consistent, which I've pointed to through these comments. I doubt we'd lose any points even if we didn't change these, but I suppose there's no harm to doing it.

2023-05-21 09:25 UTC, wq12li commented on frontend/src/main/components/Books/BookTable.js
> +            Header: 'TITLE',
`TITLE`->`Title`

2023-05-21 09:25 UTC, wq12li commented on frontend/src/main/components/Books/BookTable.js
> +            Header: 'AUTHOR',
`AUTHOR`->`Author`

2023-05-21 09:25 UTC, wq12li commented on frontend/src/main/pages/Books/BookDetailsPage.js
> +        <h1>book Details</h1>
`book`->`Book`

2023-05-21 09:25 UTC, wq12li commented on frontend/src/tests/components/Books/BookTable.test.js
> +		const expectedHeaders = ["id", "TITLE", "AUTHOR","Description"];
`"TITLE", "AUTHOR"`->`"Title", "Author"`

2023-05-21 20:27 UTC, nickzahlis commented
lgtm

2023-05-21 20:32 UTC, khtran1 requested changes
lgtm, but I second Yiu-Shing's comments; despite not losing any points most likely, it would be best to stay consistent in formatting.

2023-05-22 01:58 UTC, wq12li approved these changes
Looks good now.

2023-05-22 03:33 UTC, merged